### ISSUE TITLE
pbcopy Doesn't Work with Firefox or Slack

### ISSUE THREAD

**Issue by kevinjfoley** [jkitchin/ox-clip#13]
I've found that while I can paste content into Chrome, there's nothing pasted in Firefox or Slack. 

After a lot of troubleshooting I realized it's because the text attribute of the clipboard needs to be set (even if it's blank 🤷) and came up with this solution using Apple Script:

```bash
echo "<b>bolded text</b>" |\
hexdump -ve '1/1 "%.2x"' |\
xargs printf "set the clipboard to {text:\" \", «class HTML»:«data HTML%s»}" |\
osascript -
```

Any issue with using this approach for ` ox-clip-osx-cmd`?

**Comment by jkitchin** [comment]
You can use this variation I think:

#+BEGIN_SRC emacs-lisp
(setq ox-clip-osx-cmd "hexdump -ve '1/1 \"%.2x\"' | xargs printf \"set the clipboard to {text:\\\" \\\", «class HTML»:«data HTML%s»}\" | osascript -")
#+END_SRC

That works in Slack for me (although with no colorization), in in a google doc with color. curiously though not in a Google jamboard.

**Comment by kevinjfoley** [comment]
That variant works for me.  Do you think it makes sense to make that the default?  

> That works in Slack for me (although with no colorization), in in a google doc with color. curiously though not in a Google jamboard.

That makes sense for Slack, I don't think it supports color.  

Jamboard doesn't seem to copy to the clipboard with formatting so I'm not surprised it doesn't work pasting there either.  Does copying or pasting from Jamboard work for you in other contexts?

**Comment by NightMachinery** [comment]
Does pasting to the Discord web app work for you? What about Github? 

They don't work for me at all.

**Comment by jkitchin** [comment]
With the command described above, I cannot paste in Github or Discord. I can paste in slack (with no color as noted), and with color in Google docs.

I don't know what is special here. I guess these apps don't support pasting HTML from the clipboard.

**Comment by benthamite** [comment]
This at least does the trick:

``` emacs-lisp
(defun ox-clip-formatted-copy-advice (r1 r2)
    (interactive "r")
    (let* ((collection '(("HTML" . "hexdump -ve '1/1 \"%.2x\"' | xargs printf \"set the clipboard to {text:\\\" \\\", «class HTML»:«data HTML%s»}\" | osascript -")
			 ("Markdown" . "pandoc -f html -t markdown - | grep -v \"^:::\" | sed 's/{#.*}//g' | pbcopy")))
	   (choice (completing-read "Destination: " collection)))
      (setq ox-clip-osx-cmd (alist-get choice collection nil nil #'string=))))

  (advice-add 'ox-clip-formatted-copy :before #'ox-clip-formatted-copy-advice)
```

Note that the default value for `ox-clip-osx-cmd` (`"textutil -inputencoding UTF-8 -stdin -format html -convert rtf -stdout | pbcopy"`) does not seem to be working at all.

**Comment by jkitchin** [comment]
I added this to make different options for mac. The default value still works for me in many places, but now you can choose other options. I am a little torn on the extra work, but the only alternative would be some kind of prefix arg, and there is already a prefix arg for selecting a subtree. LMKWYK.

**Comment by benthamite** [comment]
It works well, thank you.

Minor suggestion: clarify in the `ox-clip-osx-cmd` docstring that its value can also be a string, for users who want to use a single command and bypass the prompt.

**Comment by jkitchin** [comment]
done. thanks.
