### ISSUE TITLE
Are these the same function?

### ISSUE THREAD

**Issue by AtomicNess123** [jkitchin/ox-clip#14]
I found [this code by you](https://kitchingroup.cheme.cmu.edu/blog/2016/06/16/Copy-formatted-org-mode-text-from-Emacs-to-other-applications/), and wondered if this was the old ox-clip.el or whether it does something different from `ox-clip-formatted-copy.el
`Thanks!

**Comment by jkitchin** [comment]
It is probably a precursor to the code in ox-clip.
