### ISSUE TITLE
Keeping line breaks in numbered lists

### ISSUE THREAD

**Issue by ngleb** [jkitchin/ox-clip#7]
Is it possible to keep line breaks and not break numbers for lists like this one? Or just regular line breaks?

For example:
```
1. Line 1
   Line 2 with indentation
2. Line 3
3. etc.
```

**Comment by jkitchin** [comment]
I don't think so, that doesn't export to html preserving the line breaks I think.

**Comment by ngleb** [comment]
It looks like this does help:
```
@@html:<br>@@
```
```
1. Line 1@@html:<br>@@Line 2 with indentation
2. Line 3
3. etc.
```

I use this one file for storing some texts which I often need to export to clipboard in HTML, so keeping html tags does work for me.
